temperature_max_historical:
  provider: IMD Pune
  description: Daily gridded maximum temperature, 1.0 x 1.0 degree, 1951-2024
  url: https://imdpune.gov.in/cmpg/Griddata/Max_1_Bin.html
rainfall_historical:
  provider: IMD Pune
  description: Daily gridded rainfall, 0.25 x 0.25 degree, 1901-2024
  url: https://www.imdpune.gov.in/cmpg/Griddata/Rainfall_25_NetCDF.html
temperature_max_realtime:
  provider: IMD Pune
  description: Daily maximum temperature, 0.5 x 0.5 degree, real-time binary files
  url: https://www.imdpune.gov.in/cmpg/Realtimedata/max/Max_Download.html
temperature_min_realtime:
  provider: IMD Pune
  description: Daily minimum temperature, 0.5 x 0.5 degree, real-time binary files
  url: https://imdpune.gov.in/cmpg/Realtimedata/min/Min_Download.html
